<?php

/*
 * This file is part of the IAKPress package.
 *
 * (c) IAKPress <contact@iakpress.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Joosorol\WP;

use App\Joosorol\IAKPress\IAPost\Constants;
use App\Joosorol\IAKPress\IALabel\Labels;
use App\Joosorol\IAKPress\IAPost\IAFieldType\Common\Option;
use App\Joosorol\IAKPress\IAPost\IATemplate\IASection\SignUpSection;

/**
 * class WPFieldLabels
 */
class WPFieldLabels implements Labels
{
    private array $labels;

    public function __construct()
    {
        $this->labels = [
            Option::YES => __('Yes', Constants::IAKPRESS),
            Option::NO => __('No', Constants::IAKPRESS),
			Option::POST_CONFIG_LAYOUT => __('Layout', Constants::IAKPRESS),
            Option::HEADING_TAG => __('Heading tag', Constants::IAKPRESS),
            Option::HEADING_TEXT => __('Heading text', Constants::IAKPRESS),
            Option::IMAGE_SIZE_TYPE => __('Img Size', Constants::IAKPRESS),
            Option::IMAGE_OPACITY => __('Image Opacity', Constants::IAKPRESS),
            Option::BG_COLOR => __('BG Color', Constants::IAKPRESS),
            Option::FILE_PATH => __('File Path', Constants::IAKPRESS),
            Option::FEATURED_VIDEO_PATH => __('Video url', Constants::IAKPRESS),
            Option::WEIGHT => __('Weight', Constants::IAKPRESS),
            Option::DIMENSIONS => __('Dimensions', Constants::IAKPRESS),
            Option::ACTION_URL => __('Action URL', Constants::IAKPRESS),
            Option::MEDIA_PATH => __('URL', Constants::IAKPRESS),
            Option::ICON_CLASS => __('Icon Class', Constants::IAKPRESS),
            Option::IMAGE_THUMBNAIL_PATH => __('Thumbnail', Constants::IAKPRESS),
            Option::IMAGE_FULL_PATH => __('Featured Image', Constants::IAKPRESS),
            Option::FEATURED => __('Featured', Constants::IAKPRESS),
            Option::THUMB_PATH => __('Thumbnail', Constants::IAKPRESS),
            Option::PARENT_FIELD => __('Parent field', Constants::IAKPRESS),
            Option::BG_IMG => __('BG Image', Constants::IAKPRESS),
            Option::MENU_ORDER => __('Menu order', Constants::IAKPRESS),
            Option::SCORE_VALUE => __('Score value', Constants::IAKPRESS),
            Option::PRICE_VALUE => __('Price value', Constants::IAKPRESS),
            Option::FIELD_TYPE => __('Field type', Constants::IAKPRESS),
            Option::MODEL_TYPE => __('Data list type', Constants::IAKPRESS),
            Option::TRIGGER_TYPE => __('Trigger type', Constants::IAKPRESS),
            Option::MODEL_ID => __('Data list', Constants::IAKPRESS),
            Option::SUB_MODEL_ID => __('Sub List', Constants::IAKPRESS),
            Option::NAV_MENU_ID => __('Data set', Constants::IAKPRESS),
            Option::CHOICE_TYPE => __('Choice type', Constants::IAKPRESS),
            Option::CONTENT_TYPE => __('Post type', Constants::IAKPRESS),
            Option::CONTENT_TITLE => __('Post', Constants::IAKPRESS),
            Option::CONTENT => __('Content', Constants::IAKPRESS),
            Option::DESCRIPTION => __('Description', Constants::IAKPRESS),
            Option::SHORT_DESCRIPTION => __('Short Description', Constants::IAKPRESS),
            Option::TEMPLATE => __('Template', Constants::IAKPRESS),
            Option::PATTERN => __('Pattern', Constants::IAKPRESS),
            Option::MIN_LENGTH => __('Min length', Constants::IAKPRESS),
            Option::MIN_MAX_LENGTH => __('Min/Max length', Constants::IAKPRESS),
            Option::MIN_MAX_CHOICES => __('Min/Max choices', Constants::IAKPRESS),
            Option::LABELGROUP_CLASS => __('Form label-group class', Constants::IAKPRESS),
            Option::INPUTGROUP_CLASS => __('Form input-group class', Constants::IAKPRESS),
            Option::ITEMS_HIDE_CHECKMARK => __('Hide Checkmark', Constants::IAKPRESS),
            Option::VALUE => __('Value', Constants::IAKPRESS),
            Option::DEFAULT_VALUE => __('Default value', Constants::IAKPRESS),
            Option::TITLE => __('Title', Constants::IAKPRESS),
            Option::SUB_TITLE => __('Sub title', Constants::IAKPRESS),
            Option::PRICE => __('Price', Constants::IAKPRESS),
            Option::QTY => __('Quantity', Constants::IAKPRESS),
            Option::DEFAULT_FIELD_SECTION => __('Default Section', Constants::IAKPRESS),
            Option::HELP_CLASS => __('Help class', Constants::IAKPRESS),
            Option::ERROR_CLASS => __('Error class', Constants::IAKPRESS),
            Option::SUCCESS_CLASS => __('Success class', Constants::IAKPRESS),
            Option::INFO_CLASS => __('Info class', Constants::IAKPRESS),
            Option::SUCCESS_MSG => __('Success text', Constants::IAKPRESS),
            Option::INFO_MSG => __('Info text', Constants::IAKPRESS),
            Option::ERROR_MSG => __('Validation error text', Constants::IAKPRESS),
			Option::FORMAT_MSG => __('Format error text', Constants::IAKPRESS),
            Option::LINK_TARGET => __('Link target', Constants::IAKPRESS),
            Option::BEFORE_TEXT => __('Before text', Constants::IAKPRESS),
            Option::AFTER_TEXT => __('After text', Constants::IAKPRESS),
            Option::CHAR_COUNT => __('Char count', Constants::IAKPRESS),
            Option::IAK_SCORE => __('Score', Constants::IAKPRESS),
            Option::QUESTION_NAME => __('Question name', Constants::IAKPRESS),
            Option::QUESTION_TYPE => __('Question type', Constants::IAKPRESS),
            Option::ANSWER_OPTION => __('Answer option', Constants::IAKPRESS),
            Option::SCORE => __('Score', Constants::IAKPRESS),
            Option::MIN_SCORE => __('Min score', Constants::IAKPRESS),
            Option::RATE_RANGE => __('Rate range', Constants::IAKPRESS),
            Option::MAX_SCORE => __('Max score', Constants::IAKPRESS),
            Option::IS_VALID => __('Is valid', Constants::IAKPRESS),
            Option::C_VALUE => __('Value', Constants::IAKPRESS),
            Option::HIDE => __('Hide', Constants::IAKPRESS),
            Option::SKU => __('SKU', Constants::IAKPRESS),
            Option::EXTERNAL_URL => __('External url', Constants::IAKPRESS),
            Option::ITEM_ID => __('Item ID', Constants::IAKPRESS),
            Option::GROUP_ID => __('Group name', Constants::IAKPRESS),
            Option::OPTION_ID => __('Option name', Constants::IAKPRESS),
            Option::OPTION_NAME => __('Option short name', Constants::IAKPRESS),
            Option::OPTION_LONG_NAME => __('Option long name', Constants::IAKPRESS),
            Option::OPTION_PRICE => __('Option price', Constants::IAKPRESS),
            Option::PARENT_ITEM_ID => __('Parent ID', Constants::IAKPRESS),
            Option::ITEM_TYPE => __('Item Type', Constants::IAKPRESS),
            Option::PRODUCT_TYPE => __('ProductList type', Constants::IAKPRESS),
            Option::PRODUCT_NAME => __('ProductList name', Constants::IAKPRESS),
            Option::DISABLE_PRODUCT => __('Disable product', Constants::IAKPRESS),
            Option::REGULAR_PRODUCT_PRICE => __('Regular price', Constants::IAKPRESS),
            Option::SALE_PRODUCT_PRICE => __('Sale price', Constants::IAKPRESS),
            Option::CPT_NAME => __('Slug', Constants::IAKPRESS),
            Option::CATEGORY_DEPTH => __('Category depth', Constants::IAKPRESS),
            Option::PRIMARY_CATEGORY_GROUP => __('Primary category group', Constants::IAKPRESS),
            Option::SECONDARY_CATEGORY_GROUP => __('Secondary category group', Constants::IAKPRESS),
            Option::TERTIARY_CATEGORY_GROUP => __('Tertiary category group', Constants::IAKPRESS),
            Option::TAG_GROUP => __('Tag group', Constants::IAKPRESS),
            Option::CPT_LABEL => __('Plural label', Constants::IAKPRESS),
            Option::CPT_VIEW_ID => __('View id', Constants::IAKPRESS),
            Option::CPT_SINGULAR_LABEL => __('Singular label', Constants::IAKPRESS),
            Option::POST_CONFIG_BG_COLOR => __('Background color', Constants::IAKPRESS),
            Option::TEXT_COLOR => __('Text color', Constants::IAKPRESS),
            Option::ITEMS_HOVER_BG_COLOR => __('Hover bg color', Constants::IAKPRESS),
            Option::ITEMS_HOVER_TEXT_COLOR => __('Hover text color', Constants::IAKPRESS),
            Option::SELECTED_ITEM_BG_COLOR => __('Selected bg color', Constants::IAKPRESS),
            Option::SELECTED_ITEM_TEXT_COLOR => __('Selected text color', Constants::IAKPRESS),
            Option::CHECKMARK_BG_COLOR => __('Checkmark bg color', Constants::IAKPRESS),
            Option::CHECKMARK_BORDER_COLOR => __('Checkmark border color', Constants::IAKPRESS),
            Option::POST_CONFIG_BG_IMG => __('Background image', Constants::IAKPRESS),
            Option::POST_CONFIG_BG_OPACITY => __('Background opacity', Constants::IAKPRESS),
            Option::POST_CONFIG_BG_MIN_HEIGHT => __('Background min height', Constants::IAKPRESS),
            Option::IMG_MIN_HEIGHT => __('Thumb min height', Constants::IAKPRESS),
            Option::IMG_OPACITY => __('Opacity', Constants::IAKPRESS),
            Option::POST_CONFIG_BODY_CLASS => __('Main class', Constants::IAKPRESS),
            Option::COLUMN_WIDTH => __('Display box width', Constants::IAKPRESS),
            Option::COLUMN_HEIGHT => __('Display box height', Constants::IAKPRESS),
            Option::ITEMS_MAIN_COLUMN => __('Main container', Constants::IAKPRESS),
            Option::ITEMS_HEADER_COLUMN => __('Header container', Constants::IAKPRESS),
            Option::ITEMS_FOOTER_COLUMN => __('Footer container', Constants::IAKPRESS),  
            Option::REF_TYPE => __('Post type', Constants::IAKPRESS),
            Option::REF_ARCHIVE_VIEW_ID => __('Archive view', Constants::IAKPRESS),
            Option::REF_SINGLE_VIEW_ID => __('Single view', Constants::IAKPRESS),
            Option::IAK_FIELD => __('Reference', Constants::IAKPRESS),
            Option::IAK_POST => __('Post', Constants::IAKPRESS),
            Option::ITEMS_CONTAINER_WIDTH => __('ContainerField width', Constants::IAKPRESS),
            Option::ENABLE_SHOPPING_CART => __('Enable shopping cart', Constants::IAKPRESS),
            Option::LOGIN_REQUIRED => __('Login required', Constants::IAKPRESS),
            Option::ITEMS_PER_ROW => __('Items per row', Constants::IAKPRESS),
            Option::ITEMS_THUMB_WIDTH => __('Item box width', Constants::IAKPRESS),
            Option::ITEMS_THUMB_SIZE => __('Item image size', Constants::IAKPRESS),
            Option::ITEMS_PER_PAGE => __('Items per page', Constants::IAKPRESS),
            Option::ITEMS_ORDER_BY => __('Order by', Constants::IAKPRESS),
            Option::ITEMS_ORDER_DIRECTION => __('Order direction', Constants::IAKPRESS),
            Option::COLUMNS_COUNT => __('Columns count', Constants::IAKPRESS),
            Option::IMG_HEIGHT => __('Height', Constants::IAKPRESS),
            Option::IMAGE_PATH => __('Image url', Constants::IAKPRESS),
            Option::TARGET_URL => __('Target url', Constants::IAKPRESS),
            Option::DOWNLOAD_URL => __('Download url', Constants::IAKPRESS),
            Option::IMG_WIDTH => __('Width', Constants::IAKPRESS),
            Option::ITEMS_IMG_OPACITY => __('Image Opacity', Constants::IAKPRESS),
            Option::ITEMS_MIN_HEIGHT => __('Height', Constants::IAKPRESS),
            Option::ITEMS_MIN_WIDTH => __('Width', Constants::IAKPRESS),
            Option::ITEMS_BG_COLOR => __('Bg Color', Constants::IAKPRESS),
            Option::ITEMS_BORDER_COLOR => __('Border color', Constants::IAKPRESS),
            Option::ITEMS_LAYOUT => __('Layout', Constants::IAKPRESS),
            Option::ITEMS_CLASS => __('Item Class', Constants::IAKPRESS),
            Option::ITEMS_ENABLE_PURCHASE => __('Enable Purchase', Constants::IAKPRESS),
            Option::ITEMS_STYLE => __('Item Style', Constants::IAKPRESS),
            Option::ITEMS_LINK_CLASS => __('Link class', Constants::IAKPRESS),
            Option::REVERSE => __('Reverse', Constants::IAKPRESS),
            Option::POST_TYPE => __('Post Type', Constants::IAKPRESS),
            Option::LIST_ITEMS_PER_ROW => __('List-Item width', Constants::IAKPRESS),
            Option::PAGE_NAME => __('Page', Constants::IAKPRESS),
            Option::SECTION_NAME => __('Section', Constants::IAKPRESS),
            Option::CHECK_GROUP_1 => __('check_group1', Constants::IAKPRESS),
            Option::DISABLED => __('Disabled', Constants::IAKPRESS),
            Option::HELP => __('Help Text', Constants::IAKPRESS),
            Option::LABEL => __('Label', Constants::IAKPRESS),
            Option::NAME => __('Name', Constants::IAKPRESS),
            Option::SHORT_NAME => __('Short Name', Constants::IAKPRESS),
            Option::LONG_LABEL => __('Description', Constants::IAKPRESS),
            Option::REQUIRED => __('Required', Constants::IAKPRESS),
            Option::READONLY => __('ReadOnly', Constants::IAKPRESS),
            Option::HIDE_LABEL => __('Hide Label', Constants::IAKPRESS),
            Option::ENABLED => __('Enable', Constants::IAKPRESS),
            Option::UNIQUE => __('Unique', Constants::IAKPRESS),
            Option::FIELD_WIDTH => __('Grid', Constants::IAKPRESS),
            Option::LABEL_WIDTH => __('Label width', Constants::IAKPRESS),
            Option::ROW_WIDTH => __('Column width', Constants::IAKPRESS),
            Option::TRIM => __('Trim', Constants::IAKPRESS),
            Option::PLACEHOLDER => __('Placeholder', Constants::IAKPRESS),
            Option::MAX_LENGTH => __('Max length', Constants::IAKPRESS),
            Option::ROW_CLASS => __('Form row class', Constants::IAKPRESS),
            Option::ROW_STYLE => __('Style', Constants::IAKPRESS),
            Option::LABEL_CLASS => __('Form label class', Constants::IAKPRESS),
            Option::INPUT_CLASS => __('Form input class', Constants::IAKPRESS),
            Option::LABEL_STYLE => __('Label style', Constants::IAKPRESS),
            Option::ROW_CLASS => __(   'Form row class', Constants::IAKPRESS),
            Option::LABEL_CLASS => __('Form label class', Constants::IAKPRESS),
            Option::INPUT_CLASS => __('Form input class', Constants::IAKPRESS),
            Option::SECTION_ROW_CLASS => __(   'Section row class', Constants::IAKPRESS),
            Option::SECTION_LABEL_CLASS => __('Section label class', Constants::IAKPRESS),
            Option::SECTION_INPUT_CLASS => __('Section input class', Constants::IAKPRESS),
            Option::INPUT_STYLE => __('Input style', Constants::IAKPRESS),
            Option::DELETE => __('Delete', Constants::IAKPRESS),
            Option::DATA => __('Data', Constants::IAKPRESS),
            Option::IS_MENU_ITEM => __('Is menu item', Constants::IAKPRESS),
            Option::NAV_MENU_TYPE => __('NavMenu', Constants::IAKPRESS),
            Option::CONFIG_TYPE => __('Config type', Constants::IAKPRESS),
            Option::FEATURED_IMAGE => __('Featured image', Constants::IAKPRESS),
            Option::THUMBNAIL_IMAGE => __('Thumbnail image', Constants::IAKPRESS),
            Option::THUMBNAIL_IMAGE_WIDTH => __('Thumbnail image width', Constants::IAKPRESS),
            Option::THUMBNAIL_IMAGE_HEIGHT => __('Thumbnail image height', Constants::IAKPRESS),
            Option::LARGE_IMAGE_WIDTH => __('Large image width', Constants::IAKPRESS),
            Option::LARGE_IMAGE_HEIGHT => __('Large image height', Constants::IAKPRESS),
            Option::CHECKOUT_FORM_ID => __('Checkout form', Constants::IAKPRESS),
            Option::CHECKOUT_FORM_LABEL => __('Checkout label', Constants::IAKPRESS),
            Option::CURRENCY_CODE => __('Currency code', Constants::IAKPRESS),
            Option::CURRENCY_POSITION => __('Currency position', Constants::IAKPRESS),
            Option::CURRENCY_POSITION_LEFT => __('Left', Constants::IAKPRESS),
            Option::CURRENCY_POSITION_RIGHT => __('Right', Constants::IAKPRESS),
            Option::CURRENCY_POSITION_LEFT_SPACE => __('Left space', Constants::IAKPRESS),
            Option::CURRENCY_POSITION_RIGHT_SPACE => __('Right space', Constants::IAKPRESS),
            Option::DATE_LOCALE_CODE => __('Date locale code', Constants::IAKPRESS),
            Option::PRIMARY_CATEGORY => __('Category', Constants::IAKPRESS),
            Option::CATEGORY_LVL1 => __('Category Level 1', Constants::IAKPRESS),
            Option::CATEGORY_LVL2 => __('Category Level 2', Constants::IAKPRESS),
            Option::CATEGORY_LVL3 => __('Category Level 3', Constants::IAKPRESS),
            Option::CATEGORY_LVL4 => __('Category Level 4', Constants::IAKPRESS),
            Option::CATEGORY_LVL5 => __('Category Level 5', Constants::IAKPRESS),
            Option::TAG => __('Tag', Constants::IAKPRESS),
            Option::SLUG => __('Slug', Constants::IAKPRESS),
            Option::OPTIONGROUP  => __('Option Group', Constants::IAKPRESS),
            Option::OPTIONGROUPS  => __('Option Groups', Constants::IAKPRESS),
            Option::OPTIONGROUP_TYPE  => __('Group type', Constants::IAKPRESS),
            Option::IMAGE_LIST => __('Image List', Constants::IAKPRESS),
            Option::PRODUCT_LIST => __('Product List', Constants::IAKPRESS),
            Option::SELECT_BTN_LBL => __('Add to cart', Constants::IAKPRESS),
            Option::HTTP_POST_URL => __('Post Url', Constants::IAKPRESS),
            Option::HTTP_REDIRECT_URL => __('Redirect Url', Constants::IAKPRESS),
            Option::ENABLED => __('Enable', Constants::IAKPRESS),
            Option::RANGE => __('Range', Constants::IAKPRESS),
            Option::RANGE_MIN => __('Range Min', Constants::IAKPRESS),
            Option::RANGE_MAX => __('Range Max', Constants::IAKPRESS),
			Option::COLOR => __('Color', Constants::IAKPRESS),
			Option::MAIN_SECTION => __('General', Constants::IAKPRESS),
            Option::READ_MORE_URL => __('', Constants::IAKPRESS),
            Option::READ_MORE => __('Read more', Constants::IAKPRESS),
            Option::TEXT_LINES  => __('', Constants::IAKPRESS),
            Option::BODY_SECTION => __('Body', Constants::IAKPRESS),
            Option::SAVE => __('Save', Constants::IAKPRESS),
            Option::SAVE_AND_ADD_OTHER => __('Save and add another', Constants::IAKPRESS),
            Option::SHIPPING_SECTION  => __('Shipping', Constants::IAKPRESS),
            Option::DESC_SECTION => __('Description', Constants::IAKPRESS),
            Option::FULL_DESC => __('Description', Constants::IAKPRESS),
            Option::PHOTO_GALLERY  => __('Photo Gallery', Constants::IAKPRESS),
            Option::GALLERY_SECTION  => __('Photo Gallery', Constants::IAKPRESS),
            Option::PRODVARIANT_SECTION => __('Options', Constants::IAKPRESS),
            Option::LINKEDPROD_SECTION => __('Linked Products', Constants::IAKPRESS),
            Option::SALE_START_DATE => __('Sale start date', Constants::IAKPRESS),
            Option::SALE_END_DATE => __('Sale end date', Constants::IAKPRESS),
            Option::SALE_PERIOD => __('Sale period', Constants::IAKPRESS),
            Option::IMG_LIST  => __('Image list', Constants::IAKPRESS),

            Option::USERNAME => __('Username', Constants::IAKPRESS),
            Option::EMAIL => __('Email', Constants::IAKPRESS),
            Option::PASSWORD => __('Password', Constants::IAKPRESS),
            Option::NEW_PASSWORD => __('New password', Constants::IAKPRESS),
            Option::CONFIRM_PASSWORD => __('Confirm password', Constants::IAKPRESS),
            Option::USER_LOGGED_IN => __('User is already logged in', Constants::IAKPRESS),
            Option::SIGN_UP => __('Sign Up', Constants::IAKPRESS),
            Option::LOG_IN => __('Log In', Constants::IAKPRESS),
            Option::REMEMBER_ME => __('Remember Me', Constants::IAKPRESS),
            Option::CHANGE_PASSWORD => __('Change Password', Constants::IAKPRESS),
            Option::MODIFY_PROFIL => __('Modify', Constants::IAKPRESS),
            Option::RESET_PASSWORD => __('Reset Password', Constants::IAKPRESS),
            Option::SIGN_UP_ADMIN_NOTIF => __('Sign Up - Admin Notification', Constants::IAKPRESS),
            Option::SIGN_UP_USER_NOTIF => __('Sign Up - User Notification', Constants::IAKPRESS),
            Option::RESET_PASSWORD_NOTIF => __('Reset Password - Notification', Constants::IAKPRESS),

            Option::OPT_GROUP_COLOR  => __('Color', Constants::IAKPRESS),
            Option::OPT_GROUP_SIZE => __('Size - Notification', Constants::IAKPRESS),
            Option::OPT_GROUP_CUSTOM => __('Custom', Constants::IAKPRESS),
			
			Option::TAGS  => __('Tags', Constants::IAKPRESS),
            Option::OPTIONSGROUP  => __('Options Group', Constants::IAKPRESS),
            Option::CATEGORIES  => __('Categories', Constants::IAKPRESS),
            Option::SELECT_FORM  => __('Select Form', Constants::IAKPRESS),

            Option::STEPS_STYLE => __('Steps Style', Constants::IAKPRESS),
            Option::STYLES => __('Styles', Constants::IAKPRESS),
            Option::GENERAL_STYLE => __('General Style', Constants::IAKPRESS),
            Option::ADVANCED_STYLE => __('Advanced Style', Constants::IAKPRESS),


            Option::STEP_FORM_ENABLED => __('Enable multi step form', Constants::IAKPRESS),
            Option::HIDE_PREV_BTN  => __('Hide Prev button in last step', Constants::IAKPRESS),

            Option::STEP_PREV_BTN_LBL => __('Label for prev button', Constants::IAKPRESS),
            Option::STEP_NEXT_BTN_LBL => __('Label for next button', Constants::IAKPRESS),
    
            Option::STEP_BTN_C_CLS => __('Button container class', Constants::IAKPRESS),
            Option::STEP_BTN_R_CLS => __('Button row class', Constants::IAKPRESS),
            Option::STEP_BTN_CLS => __('Button column class', Constants::IAKPRESS),
            Option::STEP_PREVBTN_CLS => __('Prev button class', Constants::IAKPRESS),
            Option::STEP_NEXTBTN_CLS => __('Next button class', Constants::IAKPRESS),
    
            Option::STEP_IND_C_CLS => __('Indicator container class', Constants::IAKPRESS),
            Option::STEP_IND_R_CLS => __('Indicator row class', Constants::IAKPRESS),
            Option::STEP_IND_CLS => __('Indicator column class', Constants::IAKPRESS),
            Option::STEP_IND_A_CLS => __('Indicator active class', Constants::IAKPRESS),


            Option::PASSWORD_ERROR_MSG => __('The password must be at least six characters and should be a mix of uppercase and lowercase characters, numbers and punctuation.', Constants::IAKPRESS)



			/*Option::LI_CLASS_LABEL = 'Container Class';
			Option::LI_IMAGE_CLASS_LABEL = 'Image Class';
			Option::LI_LABEL_CLASS_LABEL = 'Label Class';
			Option::LI_SELECTED_CLASS_LABEL = 'Selected Item Class';
			Option::LI_CHECKMARK_CLASS_LABEL = 'Checkmark Class';
			Option::ITEMS_HIDE_CHECKMARK_LABEL = 'Hide Checkmark';
			Option::LI_HIDE_LABEL_LABEL = 'Hide Label';*/

        ];
    }

    public function getLabels(): array
    {
        return $this->labels;
    }

    public function getLabelByKey(string $key, string $defaultValue = null) : string {
        if (isset($this->labels[$key])) {
            return $this->labels[$key];
        }

        return !empty($defaultValue) ? $defaultValue : $key;
    }
}
